export const PRESETS = {
  'piano-physics': {
    label: 'Jam Session Mode',
    appMode: 'sound-board',
    primaryMode: 'piano',
    pianoPhysicsMode: true,
    cloudsEnabled: false,
    multiNodeEnabled: false,
    noteInstrument: 'piano',
    noteLayout: 'causal-universe',
    masterVolume: 0.8,
    synthVolume: 0.42,
    visualReactivity: 1.15,
    universeScale: 1,
    ringInstanceCount: 48,
    particleTransfer: 0.55,
    particleCount: 84000,
    fieldStrength: 0.92,
    recursiveStrength: 0,
    travelSpeed: 0,
    particleSize: 0.17,
    bloomStrength: 0.46,
    fogDensity: 0.002,
    volumetricDensity: 0,
    volumetricScale: 0,
    trailStrength: 2.15,
    dotOpacity: 0.045,
    trailOpacity: 3.1,
    trailPersistence: 0.965,
    trailWidth: 0.024,
    memoryInfluence: 0,
    structureInfluence: 0,
    paletteShift: 0,
    colorGrade: [0.86, 1.02, 1.08],
    contrast: 1.14,
    saturation: 1.18,
    fovBreathing: 0,
    boardRadius: 46,
    torusMajorRadius: 46,
    torusMinorRadius: 15,
    torusStrength: 1.45,
    gravityStrength: 0.42,
    nodeCount: 1,
    interactionStrength: 0.3,
    particleExchange: 0.25,
    cymaticStrength: 0,
    shockwaveStrength: 0.9,
    vortexStrength: 0.35,
    fieldlineDensity: 0.8,
    audioSensitivity: 3.1,
    onsetSensitivity: 1.9,
    cloudDensity: 0,
    particleEnergy: 1.35,
    cosmicGlow: 1.15,
    cleanFlow: true
  },
  'ferrofluid-bloom': {
    label: 'Ferrofluid Bloom',
    appMode: 'sound-board',
    particleCount: 110000,
    fieldStrength: 1.15,
    recursiveStrength: 0.04,
    travelSpeed: 0,
    particleSize: 0.24,
    bloomStrength: 0.58,
    fogDensity: 0.006,
    volumetricDensity: 0.002,
    volumetricScale: 0.12,
    trailStrength: 2.8,
    dotOpacity: 0.075,
    trailOpacity: 4.6,
    trailPersistence: 0.965,
    trailWidth: 0.014,
    memoryInfluence: 0.12,
    structureInfluence: 0.02,
    paletteShift: 0.14,
    colorGrade: [0.62, 1.16, 1.28],
    contrast: 1.3,
    saturation: 1.05,
    fovBreathing: 0.03,
    boardRadius: 42,
    nodeCount: 3,
    interactionStrength: 1.0,
    particleExchange: 0.8,
    cymaticStrength: 1.15,
    shockwaveStrength: 1.55,
    vortexStrength: 1.05,
    fieldlineDensity: 1.1,
    audioSensitivity: 2.8,
    onsetSensitivity: 1.65,
    cleanFlow: true
  },
  'binary-stars': {
    label: 'Binary Stars',
    appMode: 'sound-board',
    particleCount: 100000,
    boardRadius: 40,
    nodeCount: 2,
    interactionStrength: 1.35,
    particleExchange: 1.05,
    audioSensitivity: 3.0,
    cosmicGlow: 1.35,
    trailOpacity: 4.8,
    trailPersistence: 0.97,
    bloomStrength: 0.66,
    cleanFlow: true
  },
  'three-body-nebula': {
    label: 'Three-Body Nebula',
    appMode: 'sound-board',
    particleCount: 110000,
    boardRadius: 42,
    nodeCount: 3,
    interactionStrength: 1.25,
    particleExchange: 1.1,
    audioSensitivity: 3.2,
    cosmicGlow: 1.35,
    trailOpacity: 5.0,
    trailPersistence: 0.972,
    bloomStrength: 0.68,
    cleanFlow: true
  },
  'vocal-jellyfish-cluster': {
    label: 'Vocal Jellyfish Cluster',
    appMode: 'sound-board',
    particleCount: 105000,
    boardRadius: 42,
    nodeCount: 3,
    interactionStrength: 1.05,
    particleExchange: 1.4,
    audioSensitivity: 3.5,
    cosmicGlow: 1.28,
    cymaticStrength: 1.65,
    vortexStrength: 1.45,
    paletteShift: 0.22,
    cleanFlow: true
  },
  'bass-gravity-well': {
    label: 'Bass Gravity Well',
    appMode: 'sound-board',
    particleCount: 105000,
    boardRadius: 44,
    nodeCount: 3,
    interactionStrength: 1.65,
    particleExchange: 0.75,
    audioSensitivity: 3.0,
    shockwaveStrength: 2.2,
    cosmicGlow: 1.42,
    paletteShift: 0.94,
    cleanFlow: true
  },
  'spark-constellation': {
    label: 'Spark Constellation',
    appMode: 'sound-board',
    particleCount: 95000,
    boardRadius: 42,
    nodeCount: 3,
    interactionStrength: 0.9,
    particleExchange: 1.55,
    audioSensitivity: 3.8,
    cosmicGlow: 1.5,
    trailWidth: 0.012,
    paletteShift: 0.62,
    cleanFlow: true
  },
  'cosmic-choir': {
    label: 'Cosmic Choir',
    appMode: 'sound-board',
    particleCount: 115000,
    boardRadius: 43,
    nodeCount: 4,
    interactionStrength: 1.3,
    particleExchange: 1.25,
    audioSensitivity: 3.4,
    cosmicGlow: 1.45,
    trailOpacity: 5.2,
    bloomStrength: 0.72,
    cleanFlow: true
  },
  'dense-ribbon-sculpture': {
    label: 'Dense Ribbon Sculpture',
    appMode: 'sound-board',
    particleCount: 130000,
    fieldStrength: 1.18,
    recursiveStrength: 0.04,
    travelSpeed: 0,
    particleSize: 0.16,
    bloomStrength: 0.58,
    fogDensity: 0.008,
    volumetricDensity: 0.003,
    volumetricScale: 0.14,
    trailStrength: 3.5,
    dotOpacity: 0.025,
    trailOpacity: 5.0,
    trailPersistence: 0.985,
    trailWidth: 0.026,
    trailStyle: 'ribbon-field',
    cloudDensity: 0.95,
    particleEnergy: 1.15,
    audioReactivity: 1.25,
    cosmicGlow: 1.25,
    cloudTint: [0.7, 1.1, 1.35],
    memoryInfluence: 0.08,
    structureInfluence: 0.01,
    paletteShift: 0.08,
    colorGrade: [0.75, 1.22, 1.35],
    contrast: 1.28,
    saturation: 1.08,
    boardRadius: 44,
    cymaticStrength: 1.2,
    shockwaveStrength: 1.35,
    vortexStrength: 1.35,
    fieldlineDensity: 1.6,
    cleanFlow: true
  },
  'audio-shockwave-demo': {
    label: 'Audio Shockwave Demo',
    appMode: 'sound-board',
    particleCount: 100000,
    fieldStrength: 1.25,
    recursiveStrength: 0.02,
    travelSpeed: 0,
    particleSize: 0.2,
    bloomStrength: 0.62,
    fogDensity: 0.01,
    volumetricDensity: 0.004,
    volumetricScale: 0.16,
    trailStrength: 3.0,
    dotOpacity: 0.045,
    trailOpacity: 4.2,
    trailPersistence: 0.95,
    trailWidth: 0.022,
    trailStyle: 'plasma-smoke',
    memoryInfluence: 0.06,
    structureInfluence: 0,
    paletteShift: 0.96,
    colorGrade: [1.35, 0.78, 0.55],
    contrast: 1.36,
    saturation: 1.18,
    boardRadius: 45,
    cymaticStrength: 0.65,
    shockwaveStrength: 3.4,
    vortexStrength: 0.7,
    fieldlineDensity: 1.0,
    cleanFlow: true
  },
  'cymatic-mandala-debug': {
    label: 'Cymatic Mandala',
    appMode: 'sound-board',
    particleCount: 115000,
    fieldStrength: 0.98,
    recursiveStrength: 0.02,
    travelSpeed: 0,
    particleSize: 0.14,
    bloomStrength: 0.44,
    fogDensity: 0.004,
    volumetricDensity: 0.002,
    volumetricScale: 0.1,
    trailStrength: 3.2,
    dotOpacity: 0.026,
    trailOpacity: 4.6,
    trailPersistence: 0.99,
    trailWidth: 0.016,
    trailStyle: 'cymatic-threads',
    memoryInfluence: 0.04,
    structureInfluence: 0,
    paletteShift: 0.55,
    colorGrade: [0.82, 0.98, 1.5],
    contrast: 1.48,
    saturation: 0.92,
    boardRadius: 42,
    cymaticStrength: 2.6,
    shockwaveStrength: 1.1,
    vortexStrength: 0.55,
    fieldlineDensity: 1.2,
    cleanFlow: true
  },
  'electric-orbitals': {
    label: 'Electric Orbitals',
    appMode: 'sound-board',
    particleCount: 120000,
    fieldStrength: 1.5,
    recursiveStrength: 0.045,
    travelSpeed: 0,
    particleSize: 0.16,
    bloomStrength: 0.66,
    fogDensity: 0.006,
    volumetricDensity: 0.003,
    volumetricScale: 0.12,
    trailStrength: 3.4,
    dotOpacity: 0.035,
    trailOpacity: 4.7,
    trailPersistence: 0.965,
    trailWidth: 0.014,
    trailStyle: 'electric-filaments',
    memoryInfluence: 0.1,
    structureInfluence: 0.02,
    paletteShift: 0.72,
    colorGrade: [1.05, 0.82, 1.45],
    contrast: 1.4,
    saturation: 1.24,
    boardRadius: 43,
    cymaticStrength: 1.0,
    shockwaveStrength: 1.25,
    vortexStrength: 2.8,
    fieldlineDensity: 1.55,
    cleanFlow: true
  },
  'ferrofluid-starburst': {
    label: 'Ferrofluid Starburst',
    appMode: 'sound-board',
    particleCount: 125000,
    fieldStrength: 1.34,
    recursiveStrength: 0.035,
    travelSpeed: 0,
    particleSize: 0.18,
    bloomStrength: 0.6,
    fogDensity: 0.008,
    volumetricDensity: 0.003,
    volumetricScale: 0.14,
    trailStrength: 3.4,
    dotOpacity: 0.04,
    trailOpacity: 4.8,
    trailPersistence: 0.968,
    trailWidth: 0.02,
    trailStyle: 'ribbon-field',
    memoryInfluence: 0.1,
    structureInfluence: 0.01,
    paletteShift: 0.18,
    colorGrade: [0.95, 1.18, 1.0],
    contrast: 1.34,
    saturation: 1.14,
    boardRadius: 44,
    cymaticStrength: 1.25,
    shockwaveStrength: 2.1,
    vortexStrength: 1.45,
    fieldlineDensity: 1.45,
    cleanFlow: true
  },
  'plasma-mandala': {
    label: 'Plasma Mandala',
    appMode: 'sound-board',
    particleCount: 115000,
    fieldStrength: 1.25,
    recursiveStrength: 0.03,
    travelSpeed: 0,
    particleSize: 0.16,
    bloomStrength: 0.55,
    fogDensity: 0.004,
    volumetricDensity: 0.002,
    volumetricScale: 0.1,
    trailStrength: 3.1,
    dotOpacity: 0.028,
    trailOpacity: 4.1,
    trailPersistence: 0.975,
    trailWidth: 0.012,
    memoryInfluence: 0.1,
    structureInfluence: 0.02,
    paletteShift: 0.78,
    colorGrade: [1.2, 0.66, 1.35],
    contrast: 1.36,
    saturation: 1.18,
    fovBreathing: 0.02,
    boardRadius: 40,
    cymaticStrength: 1.55,
    shockwaveStrength: 1.3,
    vortexStrength: 1.55,
    fieldlineDensity: 1.25,
    cleanFlow: true
  },
  'cymatic-lattice': {
    label: 'Cymatic Lattice',
    appMode: 'sound-board',
    particleCount: 100000,
    fieldStrength: 0.95,
    recursiveStrength: 0.02,
    travelSpeed: 0,
    particleSize: 0.14,
    bloomStrength: 0.32,
    fogDensity: 0.002,
    volumetricDensity: 0.001,
    volumetricScale: 0.08,
    trailStrength: 2.45,
    dotOpacity: 0.03,
    trailOpacity: 3.3,
    trailPersistence: 0.985,
    trailWidth: 0.01,
    memoryInfluence: 0.05,
    structureInfluence: 0,
    paletteShift: 0.54,
    colorGrade: [0.72, 0.94, 1.45],
    contrast: 1.45,
    saturation: 0.88,
    fovBreathing: 0,
    boardRadius: 44,
    cymaticStrength: 2.2,
    shockwaveStrength: 0.9,
    vortexStrength: 0.45,
    fieldlineDensity: 1,
    cleanFlow: true
  },
  'magnetic-storm-board': {
    label: 'Magnetic Storm',
    appMode: 'sound-board',
    particleCount: 120000,
    fieldStrength: 1.42,
    recursiveStrength: 0.06,
    travelSpeed: 0,
    particleSize: 0.18,
    bloomStrength: 0.62,
    fogDensity: 0.008,
    volumetricDensity: 0.004,
    volumetricScale: 0.14,
    trailStrength: 3.2,
    dotOpacity: 0.04,
    trailOpacity: 4.0,
    trailPersistence: 0.955,
    trailWidth: 0.018,
    memoryInfluence: 0.16,
    structureInfluence: 0.03,
    paletteShift: 0.86,
    colorGrade: [1.15, 0.8, 1.25],
    contrast: 1.32,
    saturation: 1.22,
    fovBreathing: 0.04,
    boardRadius: 43,
    cymaticStrength: 0.9,
    shockwaveStrength: 1.5,
    vortexStrength: 2.2,
    fieldlineDensity: 1.35,
    cleanFlow: true
  },
  'deep-bass-gravity': {
    label: 'Deep Bass Gravity',
    appMode: 'sound-board',
    particleCount: 110000,
    fieldStrength: 1.05,
    recursiveStrength: 0.02,
    travelSpeed: 0,
    particleSize: 0.2,
    bloomStrength: 0.5,
    fogDensity: 0.008,
    volumetricDensity: 0.004,
    volumetricScale: 0.15,
    trailStrength: 2.9,
    dotOpacity: 0.038,
    trailOpacity: 3.8,
    trailPersistence: 0.96,
    trailWidth: 0.016,
    memoryInfluence: 0.08,
    structureInfluence: 0.01,
    paletteShift: 0.93,
    colorGrade: [1.35, 0.92, 0.65],
    contrast: 1.38,
    saturation: 1.0,
    fovBreathing: 0.02,
    boardRadius: 46,
    cymaticStrength: 0.8,
    shockwaveStrength: 2.4,
    vortexStrength: 0.8,
    fieldlineDensity: 1,
    cleanFlow: true
  },
  'vocal-ghost-trails': {
    label: 'Vocal Ghost Trails',
    appMode: 'sound-board',
    particleCount: 95000,
    fieldStrength: 0.88,
    recursiveStrength: 0.035,
    travelSpeed: 0,
    particleSize: 0.16,
    bloomStrength: 0.36,
    fogDensity: 0.01,
    volumetricDensity: 0.004,
    volumetricScale: 0.16,
    trailStrength: 2.75,
    dotOpacity: 0.026,
    trailOpacity: 3.9,
    trailPersistence: 0.988,
    trailWidth: 0.012,
    memoryInfluence: 0.12,
    structureInfluence: 0.02,
    paletteShift: 0.35,
    colorGrade: [0.74, 1.32, 1.1],
    contrast: 1.18,
    saturation: 0.96,
    fovBreathing: 0.03,
    boardRadius: 40,
    cymaticStrength: 1.35,
    shockwaveStrength: 1.0,
    vortexStrength: 1.25,
    fieldlineDensity: 1.2,
    cleanFlow: true
  },
  'clean-infinite-flow': {
    label: 'Clean Infinite Flow',
    appMode: 'tunnel',
    particleCount: 120000,
    fieldStrength: 0.52,
    recursiveStrength: 0.075,
    travelSpeed: 2.15,
    particleSize: 0.24,
    bloomStrength: 0.34,
    fogDensity: 0.01,
    volumetricDensity: 0.004,
    volumetricScale: 0.26,
    trailStrength: 2.05,
    dotOpacity: 0.045,
    trailOpacity: 3.2,
    trailPersistence: 0.94,
    trailWidth: 0.018,
    trailOnly: false,
    memoryInfluence: 0.38,
    structureInfluence: 0.12,
    paletteShift: 0.11,
    colorGrade: [0.62, 1.08, 1.18],
    contrast: 1.22,
    saturation: 0.86,
    fovBreathing: 0.12,
    scaleBandSize: 120,
    cleanFlow: true
  },
  'control-test-mode': {
    label: 'Control Test Mode',
    appMode: 'control-test',
    particleCount: 90000,
    fieldStrength: 0.72,
    recursiveStrength: 0.06,
    travelSpeed: 2.6,
    particleSize: 0.28,
    bloomStrength: 0.4,
    fogDensity: 0.008,
    volumetricDensity: 0.006,
    volumetricScale: 0.2,
    trailStrength: 2.8,
    dotOpacity: 0.045,
    trailOpacity: 3.6,
    trailPersistence: 0.97,
    trailWidth: 0.028,
    memoryInfluence: 0.2,
    structureInfluence: 0.04,
    paletteShift: 0.2,
    colorGrade: [0.9, 1.15, 1.25],
    contrast: 1.35,
    saturation: 1.05,
    fovBreathing: 0.05,
    scaleBandSize: 120,
    cleanFlow: true,
    controlTestMode: true
  },
  'abyssal-plasma': {
    label: 'Abyssal Plasma',
    particleCount: 90000,
    fieldStrength: 0.92,
    recursiveStrength: 0.14,
    travelSpeed: 2.2,
    particleSize: 2.2,
    bloomStrength: 0.95,
    fogDensity: 0.045,
    volumetricDensity: 0.055,
    volumetricScale: 0.9,
    trailStrength: 0.85,
    memoryInfluence: 0.82,
    structureInfluence: 0.62,
    paletteShift: 0.08,
    colorGrade: [0.85, 1.08, 1.32],
    contrast: 1.08,
    saturation: 1.12,
    fovBreathing: 0.65,
    scaleBandSize: 68
  },
  'golden-singularity': {
    label: 'Golden Singularity',
    particleCount: 110000,
    fieldStrength: 1.05,
    recursiveStrength: 0.18,
    travelSpeed: 2.45,
    particleSize: 2.1,
    bloomStrength: 1.18,
    fogDensity: 0.052,
    volumetricDensity: 0.07,
    volumetricScale: 0.82,
    trailStrength: 1.0,
    memoryInfluence: 0.72,
    structureInfluence: 0.85,
    paletteShift: 0.31,
    colorGrade: [1.35, 1.06, 0.55],
    contrast: 1.18,
    saturation: 1.22,
    fovBreathing: 0.82,
    scaleBandSize: 62
  },
  'crystal-void': {
    label: 'Crystal Void',
    particleCount: 64000,
    fieldStrength: 0.62,
    recursiveStrength: 0.08,
    travelSpeed: 1.65,
    particleSize: 1.9,
    bloomStrength: 0.72,
    fogDensity: 0.018,
    volumetricDensity: 0.026,
    volumetricScale: 0.62,
    trailStrength: 0.55,
    memoryInfluence: 0.52,
    structureInfluence: 0.35,
    paletteShift: 0.58,
    colorGrade: [0.72, 0.96, 1.35],
    contrast: 1.26,
    saturation: 0.86,
    fovBreathing: 0.35,
    scaleBandSize: 92
  },
  'recursive-storm': {
    label: 'Recursive Storm',
    particleCount: 120000,
    fieldStrength: 1.38,
    recursiveStrength: 0.26,
    travelSpeed: 3.25,
    particleSize: 2.55,
    bloomStrength: 1.28,
    fogDensity: 0.065,
    volumetricDensity: 0.08,
    volumetricScale: 1.02,
    trailStrength: 1.15,
    memoryInfluence: 1.02,
    structureInfluence: 0.95,
    paletteShift: 0.82,
    colorGrade: [1.25, 0.75, 1.18],
    contrast: 1.2,
    saturation: 1.34,
    fovBreathing: 1.0,
    scaleBandSize: 50
  },
  'bioluminescent-dream': {
    label: 'Bioluminescent Dream',
    particleCount: 100000,
    fieldStrength: 0.86,
    recursiveStrength: 0.16,
    travelSpeed: 2.05,
    particleSize: 2.8,
    bloomStrength: 1.08,
    fogDensity: 0.05,
    volumetricDensity: 0.065,
    volumetricScale: 1.08,
    trailStrength: 0.95,
    memoryInfluence: 0.9,
    structureInfluence: 0.7,
    paletteShift: 0.16,
    colorGrade: [0.72, 1.28, 1.08],
    contrast: 1.02,
    saturation: 1.38,
    fovBreathing: 0.68,
    scaleBandSize: 74
  },
  'event-horizon': {
    label: 'Event Horizon',
    particleCount: 130000,
    fieldStrength: 1.16,
    recursiveStrength: 0.22,
    travelSpeed: 2.8,
    particleSize: 2.35,
    bloomStrength: 1.35,
    fogDensity: 0.058,
    volumetricDensity: 0.075,
    volumetricScale: 0.95,
    trailStrength: 1.08,
    memoryInfluence: 0.86,
    structureInfluence: 1.08,
    paletteShift: 0.94,
    colorGrade: [1.28, 0.9, 0.78],
    contrast: 1.34,
    saturation: 1.08,
    fovBreathing: 1.15,
    scaleBandSize: 56
  }
};

export function applyPreset(params, presetId) {
  const preset = PRESETS[presetId] ?? PRESETS['piano-physics'];
  params.controlTestMode = false;
  params.pianoPhysicsMode = false;
  params.cloudsEnabled = true;
  params.multiNodeEnabled = true;
  Object.assign(params, preset);
  params.controlTestMode = !!preset.controlTestMode || preset.appMode === 'control-test';
  params.appMode = preset.appMode ?? 'sound-board';
  params.preset = presetId in PRESETS ? presetId : 'piano-physics';
  params.presetLabel = preset.label;
}

export function presetOptions() {
  return Object.fromEntries(Object.entries(PRESETS).map(([id, preset]) => [preset.label, id]));
}
